---
debug: true
branches: main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: refactor
          release: patch
        - type: build
          release: patch
        - type: ci
          release: patch
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
#      presetConfig:
#        types:
#          - type: refactor
#            section: Internal

  - "@semantic-release/github"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
