---
debug: true
branches: main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      releaseRules:
        - type: refactor
          release: patch
        - type: build
          release: patch
        - type: ci
          release: patch
  - - "@semantic-release/release-notes-generator"
    - preset: angular
  - "@semantic-release/github"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
