---
debug: true
branches: main
preset: conventionalcommits
plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: refactor
          release: patch
        - type: build
          release: patch
        - type: ci
          release: patch
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"
