---
blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: >
      https://github.com
      /akikanellis
      /github-action-continuous-release-test
      /discussions
    about: Please ask and answer questions here.
