---
rules:
  braces:
    level: error
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: 1
    max-spaces-inside-empty: 5
  brackets:
    level: error
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: 1
    max-spaces-inside-empty: 5
  colons:
    level: error
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    level: error
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
  comments: disable
  comments-indentation: disable
  document-end: disable
  document-start:
    level: error
    present: true
  empty-lines:
    level: error
    max: 2
    max-start: 0
    max-end: 0
  hyphens:
    level: error
    max-spaces-after: 1
  indentation:
    level: error
    spaces: consistent
    indent-sequences: true
    check-multi-line-strings: false
  key-duplicates: enable
  line-length:
    level: error
    max: 80
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  new-line-at-end-of-file: disable
  new-lines:
    type: unix
  trailing-spaces: disable
