---
name: PR Updated
"on":
  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  validate-branch-name:
    name: Validate branch name
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        uses: deepakputhraya/action-branch-name@v1.0.0
        with:
          regex: ^[a-z]+\/([a-z]|-)+$ # TODO what should this regex be? Prefixes or not?
          allowed_prefixes: break,feat,bug,chore,docs

  # TODO names for steps
  # TODO maybe don't bother with this
#  check-commits:
#    name: Check commits
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#      - name: Check commits
#        uses: aevea/commitsar@v0.18.0



#  label:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: TimonVS/pr-labeler-action@v3
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
