---
name: PR Opened
"on":
  pull_request:
    types: [opened]
    branches: [main]

jobs:
  validate-branch-name:
    name: Validate branch name
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        uses: deepakputhraya/action-branch-name@v1.0.0
        with:
          regex: ^[a-z]+\/([a-z]|-)+$ # TODO what should this regex be? Prefixes or not?
          allowed_prefixes: break,feat,bug,chore,docs
