---
name: Label Pull Request
"on":
  pull_request_target:
    branches: [main]

jobs:
  label:
    name: Label
    runs-on: ubuntu-latest
    steps:
      - name: Label
        uses: bcoe/conventional-release-labels@v1.2.2
