---
name: Test

"on":
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: echo "Test successful"
