---
name: Test

"on":
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0 editorconfig-checker-disable-line

      - name: Setup just
        # yamllint disable-line rule:line-length
        uses: extractions/setup-just@v1.4.0 # editorconfig-checker-disable-line
        with:
          # renovate: datasource=crate depName=just
          just-version: 1.1.1

      - name: Test
        run: just test
